project:
  type: website
  output-dir: docs

website:
  title: "Metabarcoding Workshop"
  site-url: https://jelmerp.github.io/metabar-ws24
  repo-url: https://github.com/jelmerp/metabar-ws24
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa home >}}"
      - text: Wed
        menu:
        - text: "1: Intro to metabarcoding (slides as PDF)"
          href: 01_intro.pdf
        - text: "2: Intro to OSC & VS Code"
          href: 02_osc.qmd
        - text: "3: Read QC & primer trimmming"
          href: 03_qc-trim.qmd
      - text: Thu
        menu:
        - text: "4: ASV/OTU calling and pipeline considerations (slides as PDF)"
          href: 04_pipeline.pdf
        - text: "5: Calling ASVs with the DADA2 pipeline"
          href: 05_dada.qmd
        - text: "6: Alpha & beta diversity statistics"
          href: 06_div.qmd
      - text: Fri
        menu:
        - text: "7: Differential abundance analysis"
          href: 07_diffabund.qmd
        - text: "8: Intro to network analysis"
          href: 08_networks.qmd
        - text: "9: Defining a core microbiome"
          href: 09_core.qmd
        - text: "10: SRA data submission"
          href: 10_sra-sub.qmd
    right:
      - text: Homework
        menu:
          - text: Instructions
            href: homework/instructions.qmd
          - text: Unix Shell
            href: homework/shell.qmd
          - text: R
            href: homework/R.qmd
      - text: Reference pages
        menu:
          - text: Literature (TBA)
          - text: Software management at OSC
            href: ref/software.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/jelmerp/metabar-ws24
          - text: Report an Issue
            url:  https://github.com/jelmerp/metabar-ws24/issues/new
  page-footer:
    left: "2024, Jelmer Poelstra"
    right:
      - icon: github
        href: https://github.com/jelmerp/pracs-sp24
format:
  html:
    highlight-style: atom-one
    theme: minty
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 900px

editor: source

